"""empty message

Revision ID: 463001a9b222
Revises: 8a2d36d73c7d
Create Date: 2021-04-20 15:39:50.390220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463001a9b222'
down_revision = '8a2d36d73c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
